### PR TITLE
Sound

### PR DESCRIPTION
**Pull request by Tuizi**
Add sounds support + upgrade ControlP5 library + remove core lib to use processing 2.0

### CODE REVIEW

**Comment by mgoimam** [comment]
The library and the audio worked great out of the box. I noticed 2 issues:

1) the main theme is not looping 
http://code.compartmental.net/minim/javadoc/ddf/minim/AudioPlayer.html#play()
Seems like music.play() disables looping. What you actually want is simply to call music.loop() inside the Audio.startPlaying() method.

2) I hear the "place" sound every frame while the game was completed
This is not an issue with the audio, but an early exit should be added in the TetrisGame.update() : 'if (this.gameOver) return;'.

**Comment by scjody** [comment]
Looks good to me, apart from @mgoimam 's comments.

By the way we're going to want to allow the theme to be changed between games, but that should be a different PR...

**Comment by Tuizi** [comment]
@mgoimam ok, I couldn't reproduce the loop issue, but I have added the loop() call in the Audio.startMudic method

I have also added the return if game is over in TetrisGame.update().
I also fixed the play again button

**Comment by mgoimam** [comment]
Looks good to me, +1!

**Comment by scjody** [comment]
:shipit: from me if you fix `btn`.  Thanks for helping!

**Comment by scjody** [comment]
Related to #5

**Comment by Tuizi** [comment]
Fixed variable name @scjody thank you

**Comment by scjody** [comment]
:shipit:

**Pull request merged**
