### PR TITLE
Features/authentic rules

### PR DESCRIPTION
**Pull request by mgoimam**
Port to java + implementation of "Indispinsible" rules according to http://tetris.wikia.com/wiki/Tetris_Guideline.

### CODE REVIEW

**Comment by StreetWanderer** [comment]
My main question about the port to Java is : **What does it gives us that Processing wasn't ?**
Processing is basically a superset of Java, so we can use Java's features.
Processing also manage all the display annoyances/problems for us with OpenGL and provides quick draw methods to create various shapes, bezier and visual effects that could save us a lot of time down the road. (And I won't go in the development environnement and export to native apps)

So, again, what does porting to pure java brings to the table? You certainly have a good reason and I'm missing something.

**Comment by mgoimam** [comment]
To clarify, I submitted a java project, but still using the Processing library. All Processing functionality remains accessible (for example, the rendering is still done in AppletRenderer using the PApplet calls).

I initially found the official IDE for Processing to be less than ideal (maybe it's just the Windows version, but it felt slow and it lacked a lot of features that Eclipse provides, like easy renaming of variables). My original intent was to develop the pure Processing code using Eclipse, but found that it deals much better with java code.

Minor point, I also had in mind of trying to try to integrate "extra" stuff like a Kinect. This seemed much easier in Java than in Processing (even if we could expose a Java library to the Processing project).

Keep in mind, I am not experienced with Processing, so may be wrong on some points. If there is a better way to set this up, I'm quite open to suggestions. I believe I can port it back to pure Processing in an hour or two without issues.

**Comment by scjody** [comment]
I've played with this a bit and I also have concerns with the pure Java approach, namely the complexity of getting the software going on a new system and the difficulty of using an environment other than Eclipse.  Despite being new to Processing, I can install it in about 5 minutes and then I'm ready to go.  I managed to install Sublime Text and the Processing plugin for that in about 10 minutes more ( https://github.com/b-g/processing-sublime ).  Getting the pure Java version going looks much more complicated ( http://www.creativeapplications.net/processing/craft-your-processing-sketches-in-eclipse/ ) and I don't see an easy way to make this work with any environment other than Eclipse without spending several hours fiddling with Java.

If you want to use Eclipse to edit Processing code instead of the Processing environment (or Sublime Text), you can install Proclipsing: https://code.google.com/p/proclipsing/ .  In fact, there seem to be Processing plugins for most common editors, including Vim and EMACS!  So nobody's forced to use the Processing environment, which does seem pretty limiting.

As for the Kinect, there is excellent support for the Kinect in Processing - probably better than Java's.  Keep in mind that Processing was designed exactly for creating interactive multimedia art, so the Kinect is a really good fit :smile_cat:

So can you please port this back to Processing?  That will give us all a better base to build on. :hammer:

**Comment by mgoimam** [comment]
Port to processing completed, it did indeed only take an hour or so!

**Comment by scjody** [comment]
@mgoimam I don't see a reasonable way to review this, so since we're at the start of the project you can go ahead and :shipit: and we'll treat this as the initial codebase.  Next time please make smaller commits - one commit per logical change, so we have a chance of being able to review things and understand what's going on.

Thanks for the work so far!!

**Pull request merged**
