### PR TITLE
Add Arduino controller input

### PR DESCRIPTION
**Pull request by scjody**
Works with an Arduino programmed with Firmata:
https://www.arduino.cc/en/reference/firmata

@mgoimam @artistcoder Look OK?

### CODE REVIEW

**Comment by scjody** [comment]
Closes #4

**Comment by mgoimam** [comment]
I can't actually run this since I don't have an arduino. Shouldn't there be a library for cc.arduino.*?

**Comment by scjody** [comment]
Re: library, cc.arduino should ship with Processing.

And I'm not expecting anyone to test this... just review the code to make sure it makes sense.

**Comment by mgoimam** [comment]
Cool, looks good then!

**Pull request merged**
